server:
    port: 8086
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:mysql://localhost:3306/DPMDatabase"
    username: "root"
    password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka