server:
    port: 8086
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:h2:mem:virtual"
    username: "sa"
    password: "password"
    jpa:
      database-platform: "org.hibernate.dialect.H2Dialect"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka